# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#-source 'https://github.com/CocoaPods/Specs.git'
target 'ZJSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
##mark 1，直接导入方式,一般打开此注释即可
   pod 'ZJSDK'#, :path => '../'
   
   
##mark 2 本地视频内容引入方式。另外还需要将ZJSDKModuleKS.a静态库拖进项目里
   #pod 'ZJSDK/ZJSDKModuleDSP'#依赖库，引入任何模块都需要依赖此模块，默认引入
   #pod 'ZJSDK/ZJSDKModuleGDT'#优量汇广告
   #pod 'ZJSDK/ZJSDKModuleCSJ'#穿山甲广告
   #pod 'ZJContentVideo', :path => '../ZJSDK/ZJSDKModuleKS'
   #pod 'ZJSDK/ZJSDKModuleMTG'#MTG广告
   #pod 'ZJSDK/ZJSDKModuleSIG'#Sigmob广告
   #pod 'ZJSDK/ZJSDKModuleBD'#百度广告
  
##mark 3，分模块导入方式
  #pod 'ZJSDK/ZJSDKModuleDSP'#依赖库，引入任何模块都需要依赖此模块，默认引入
  #pod 'ZJSDK/ZJSDKModuleGDT'#优量汇广告
  #pod 'ZJSDK/ZJSDKModuleCSJ'#穿山甲广告
  #pod 'ZJSDK/ZJSDKModuleKS'#快手广告
  #pod 'ZJSDK/ZJSDKModuleMTG'#MTG广告
  #pod 'ZJSDK/ZJSDKModuleSIG'#Sigmob广告
  #pod 'ZJSDK/ZJSDKModuleBD'#百度广告
  
##mark 4，默认不引入的广告模块
  #pod 'ZJSDK/ZJSDKModuleYM'#云码广告
  #pod 'ZJSDK/ZJSDKModuleGoogle'#Google广告
  
  
  
  
##mark 5，引入聚合广告模块
  #pod 'ZJSDK/ZJSDKModuleDSP'    #依赖库，引入任何模块都需要依赖此模块，默认引入
  
  ##聚合引入多个会引起一些联盟重复初始化的问题
  #pod 'ZJSDK/ZJSDKModuleBeiZi'  #倍孜广告
  #pod 'ZJSDK/ZJSDKModuleWM'     #Sigmob to-bid广告

  
  # Pods for ZJSDKDemo

end
 
