# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#-source 'https://github.com/CocoaPods/Specs.git'
target 'ZJSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
##mark 1，直接导入方式,一般打开此注释即可
   pod 'ZJSDK'#, :path => '../'
#如需接入内容包，需要制定本地，公共仓库的不支持内容包
#   pod 'KSAdSDK', :path => '../ZJSDK/ZJSDKModuleKS/KS'
   
##mark 2，分模块导入方式
  #pod 'ZJSDK/ZJSDKModuleDSP'#依赖库，引入任何模块都需要依赖此模块，默认引入
  #pod 'ZJSDK/ZJSDKModuleGDT'#优量汇广告
  #pod 'ZJSDK/ZJSDKModuleCSJ'#穿山甲广告
  #pod 'ZJSDK/ZJSDKModuleKS'#快手广告
  #pod 'ZJSDK/ZJSDKModuleMTG'#MTG广告
  #pod 'ZJSDK/ZJSDKModuleSIG'#Sigmob广告
  #pod 'ZJSDK/ZJSDKModuleBD'#百度广告
  #pod 'ZJSDK/ZJSDKModuleBeiZi'#倍孜广告
  #pod 'ZJSDK/ZJSDKModuleTanX'#TanX广告
  
##mark 3，默认不引入的广告模块
  #pod 'ZJSDK/ZJSDKModuleGoogle'#Google广告
  #pod 'ZJSDK/ZJSDKModulePangle'#穿山甲海外

##mark 4，引入聚合广告模块
#聚合广告模块（默认不引入）
#注意：引入多个聚合广告可能会引起一些联盟重复初始化的问题。
  #pod 'ZJSDK/ZJSDKModuleWM'     #Sigmob to-bid广告

  
  # Pods for ZJSDKDemo

end
 
