# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#-source 'https://github.com/CocoaPods/Specs.git'
target 'ZJSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
  ##mark 1，直接导入方式,一般打开此注释即可
   pod 'ZJSDK'#, :path => '../'
  
  ## #导入默认未导入模块
  ##  pod 'ZJSDK/ZJSDKModuleYM'#云码广告
  ##  pod 'ZJSDK/ZJSDKModuleGoogle', :path => '../'
  
  
  
  
  
  
  ##mark 2，分模块导入方式，如有视频内容接入需求，则注释pod 'ZJSDK/ZJSDKModuleKS'#快手广告，打开pod 'KSAdSDK', :path => '../ZJSDK/ZJSDKModuleKS'
  #pod 'ZJSDK/ZJSDKModuleDSP'
  #pod 'ZJSDK/ZJSDKModuleGDT'#优量汇广告
  #pod 'ZJSDK/ZJSDKModuleCSJ'#穿山甲广告
  #pod 'ZJSDK/ZJSDKModuleKS'#快手广告
  ##mark 2.1 分模块，单独导入本地视频内容包方式。另外还需要将ZJSDKModuleKS.a静态库拖进项目里
  ##pod 'KSAdSDK', :path => '../ZJSDK/ZJSDKModuleKS'
  #pod 'ZJSDK/ZJSDKModuleMTG'#MTG广告
  #pod 'ZJSDK/ZJSDKModuleSIG'#Sigmob广告
  #pod 'ZJSDK/ZJSDKModuleBD'#百度广告
  
  ##默认不引入的广告模块
  ##pod 'ZJSDK/ZJSDKModuleYM'#云码广告
  ##pod 'ZJSDK/ZJSDKModuleGoogle'#Google广告
  
  ## Pods for ZJSDKDemo

end
 
